# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycareprovider',
            name='lastName',
            field=models.CharField(default='ATest', max_length=200),
            preserve_default=False,
        ),
    ]
